## manipulacion de columas

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('online_retail.csv')

In [3]:
# crear una columna a partir de la operacion de dos columnas
df['TotalPrice'] = df['Quantity'] * df['UnitPrice']
print(df.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

           InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice
0  2010-12-01 08:26:00       2.55     17850.0  United Kingdom       15.30
1  2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
2  2010-12-01 08:26:00       2.75     17850.0  United Kingdom       22.00
3  2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
4  2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34

In [4]:
# columnas calculadas a partir de condicionales
df['HighValue'] = df['TotalPrice'] > 15
print(df['HighValue'].head(10))

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7    False
8    False
9     True
Name: HighValue, dtype: bool

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
 8   TotalPrice   541909 non-null  float64
 9   HighValue    541909 non-null  bool
dtypes: bool(1), float64(3), int64(1), object(5)
memory usage: 37.7+ MB

In [6]:
#cambiar el tipo de dato a fecha conversion de tipo

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
 8   TotalPrice   541909 non-null  float64
 9   HighValue    541909 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 37.7+ MB
None

In [7]:
# aplicacion de funciones lambda, este aplica a cada fila seleccionada la operacion que le especifiquemos

df['DiscountedPrice'] = df['UnitPrice'].apply(lambda x:x*0.9)
print(df.head(3))

  InvoiceNo StockCode                         Description  Quantity  \
0    536365    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                 WHITE METAL LANTERN         6
2    536365    84406B      CREAM CUPID HEARTS COAT HANGER         8

          InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom       15.30
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom       22.00

   HighValue  DiscountedPrice
0       True            2.295
1       True            3.051
2       True            2.475

In [8]:
# hacer modificaciones a columnas categoricas
def categorize_price(price):
    if price > 50:
        return 'Hight'
    elif price < 20:
        return 'Medium'
    else:
        'Low'

df['PriceCategory'] = df['UnitPrice'].apply(categorize_price)
print(df.head(3))

  InvoiceNo StockCode                         Description  Quantity  \
0    536365    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                 WHITE METAL LANTERN         6
2    536365    84406B      CREAM CUPID HEARTS COAT HANGER         8

          InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom       15.30
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom       22.00

   HighValue  DiscountedPrice PriceCategory
0       True            2.295        Medium
1       True            3.051        Medium
2       True            2.475        Medium

## Análisis de Ventas con Pandas: Agrupaciones y Estadísticas

In [9]:
# group by

country_count = df['Country'].value_counts()
print(country_count)

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

In [10]:
country_group = df.groupby('Country')['Quantity'].sum()
print(country_group)

Country
Australia                 83653
Austria                    4827
Bahrain                     260
Belgium                   23152
Brazil                      356
Canada                     2763
Channel Islands            9479
Cyprus                     6317
Czech Republic              592
Denmark                    8188
EIRE                     142637
European Community          497
Finland                   10666
France                   110480
Germany                  117448
Greece                     1556
Hong Kong                  4769
Iceland                    2458
Israel                     4353
Italy                      7999
Japan                     25218
Lebanon                     386
Lithuania                   652
Malta                       944
Netherlands              200128
Norway                    19247
Poland                     3653
Portugal                  16180
RSA                         352
Saudi Arabia                 75
Singapore                  5234
Spain                     26824
Sweden                    35637
Switzerland               30325
USA                        1034
United Arab Emirates        982
United Kingdom          4263829
Unspecified                3300
Name: Quantity, dtype: int64

In [11]:
# estadisticas agrupadas media y suma del preciomunitario por ciudad
country_stats = df.groupby('Country')['UnitPrice'].agg(['mean','sum'])
print(country_stats)

                            mean          sum
Country
Australia               3.220612     4054.750
Austria                 4.243192     1701.520
Bahrain                 4.556316       86.570
Belgium                 3.644335     7540.130
Brazil                  4.456250      142.600
Canada                  6.030331      910.580
Channel Islands         4.932124     3738.550
Cyprus                  6.302363     3920.070
Czech Republic          2.938333       88.150
Denmark                 3.256941     1266.950
EIRE                    5.911077    48447.190
European Community      4.820492      294.050
Finland                 5.448705     3786.850
France                  5.028864    43031.990
Germany                 3.966930    37666.000
Greece                  4.885548      713.290
Hong Kong              42.505208    12241.500
Iceland                 2.644011      481.210
Israel                  3.633131     1079.040
Italy                   4.831121     3879.390
Japan                   2.276145      814.860
Lebanon                 5.387556      242.440
Lithuania               2.841143       99.440
Malta                   5.244173      666.010
Netherlands             2.738317     6492.550
Norway                  6.012026     6529.060
Poland                  4.170880     1422.270
Portugal                8.582976    13037.540
RSA                     4.277586      248.100
Saudi Arabia            2.411000       24.110
Singapore             109.645808    25108.890
Spain                   4.987544    12633.450
Sweden                  3.910887     1806.830
Switzerland             3.403442     6813.690
USA                     2.216426      644.980
United Arab Emirates    3.380735      229.890
United Kingdom          4.532422  2245715.474
Unspecified             2.699574     1204.010

In [12]:
# cantidad agrupada por ciudad y po cod de stock
country_stock_group = df.groupby(['Country','StockCode'])['Quantity'].sum()
print(country_stock_group)

Country      StockCode
Australia    15036        600
             15056BL        3
             16161P       400
             16169E        25
             20665          6
                         ...
Unspecified  85180A         2
             85180B         1
             85212         12
             85213         12
             85227         10
Name: Quantity, Length: 19839, dtype: int64

In [13]:
def total_revenue( group):
    return(group['Quantity']* group['UnitPrice']).sum()

revenue_per_country = df.groupby('Country').apply(total_revenue)
print(revenue_per_country)

Country
Australia                137077.270
Austria                   10154.320
Bahrain                     548.400
Belgium                   40910.960
Brazil                     1143.600
Canada                     3666.380
Channel Islands           20086.290
Cyprus                    12946.290
Czech Republic              707.720
Denmark                   18768.140
EIRE                     263276.820
European Community         1291.750
Finland                   22326.740
France                   197403.900
Germany                  221698.210
Greece                     4710.520
Hong Kong                 10117.040
Iceland                    4310.000
Israel                     7907.820
Italy                     16890.510
Japan                     35340.620
Lebanon                    1693.880
Lithuania                  1661.060
Malta                      2505.470
Netherlands              284661.540
Norway                    35163.460
Poland                     7213.140
Portugal                  29367.020
RSA                        1002.310
Saudi Arabia                131.170
Singapore                  9120.390
Spain                     54774.580
Sweden                    36595.910
Switzerland               56385.350
USA                        1730.920
United Arab Emirates       1902.280
United Kingdom          8187806.364
Unspecified                4749.790
dtype: float64

C:\Users\luihid384\AppData\Local\Temp\ipykernel_35240\3300534677.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  revenue_per_country = df.groupby('Country').apply(total_revenue)

In [14]:
country_desc = revenue_per_country.sort_values(ascending= False)
#print(country_desc)
print("los paises con mas ventas son: \n" ,country_desc.iloc[:3])

print("los paises con menos ventas son: \n" ,country_desc.iloc[-3:])

los paises con mas ventas son:
 Country
United Kingdom    8187806.364
Netherlands        284661.540
EIRE               263276.820
dtype: float64
los paises con menos ventas son:
 Country
Czech Republic    707.72
Bahrain           548.40
Saudi Arabia      131.17
dtype: float64

In [15]:
df.head(3)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,HighValue,DiscountedPrice,PriceCategory
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,True,2.295,Medium
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,True,3.051,Medium
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,True,2.475,Medium

In [16]:
df['Total_price']= df['Quantity'] * df['UnitPrice']
df.head(3)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,HighValue,DiscountedPrice,PriceCategory,Total_price
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,True,2.295,Medium,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,True,3.051,Medium,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,True,2.475,Medium,22.00

In [17]:
# filtar ventas en el reino unido - UK

uk_sales = df[
    (df['Country']== 'United Kingdom')
]

uk_sales.head(3)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,HighValue,DiscountedPrice,PriceCategory,Total_price
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,True,2.295,Medium,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,True,3.051,Medium,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,True,2.475,Medium,22.00

In [18]:
high_quantity_sales = df[df['Quantity'] > 10].sort_values(by= 'Quantity', ascending= True)
high_quantity_sales.head(3)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,HighValue,DiscountedPrice,PriceCategory,Total_price
226427,556803,22356,CHARLOTTE BAG PINK POLKADOT,11,2011-06-14 14:57:00,2.46,NaN,United Kingdom,27.06,True,2.214,Medium,27.06
467317,576339,23265,SET OF 3 WOODEN TREE DECORATIONS,11,2011-11-14 15:27:00,2.46,14096.0,United Kingdom,27.06,True,2.214,Medium,27.06
309814,564141,21084,SET/6 COLLAGE PAPER CUPS,11,2011-08-23 11:47:00,0.19,17841.0,United Kingdom,2.09,False,0.171,Medium,2.09

In [19]:
# filtrar por varias condiciones
uk_high_quantity_sales = df[
    (df['Country']== 'United Kingdom')&
    (df['Quantity'] > 40)
].sort_values(by= 'Quantity', ascending= True)

uk_high_quantity_sales.iloc[-5:-2]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,HighValue,DiscountedPrice,PriceCategory,Total_price
421632,573008,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,4800,2011-10-27 12:26:00,0.21,12901.0,United Kingdom,1008.0,True,0.189,Medium,1008.0
74614,542504,37413,NaN,5568,2011-01-28 12:03:00,0.00,NaN,United Kingdom,0.0,False,0.000,Medium,0.0
502122,578841,84826,ASSTD DESIGN 3D PAPER STICKERS,12540,2011-11-25 15:57:00,0.00,13256.0,United Kingdom,0.0,False,0.000,Medium,0.0

In [20]:
sales_2011 = df[
    df['InvoiceDate'].dt.year == 2011
]

print(sales_2011)

       InvoiceNo StockCode                      Description  Quantity  \
42481     539993     22386          JUMBO BAG PINK POLKADOT        10
42482     539993     21499               BLUE POLKADOT WRAP        25
42483     539993     21498              RED RETROSPOT WRAP         25
42484     539993     22379         RECYCLING BAG RETROSPOT          5
42485     539993     20718        RED RETROSPOT SHOPPER BAG        10
...          ...       ...                              ...       ...
541904    581587     22613      PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899     CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254    CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255  CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138    BAKING SET 9 PIECE RETROSPOT          3

               InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
42481  2011-01-04 10:00:00       1.95     13313.0  United Kingdom       19.50
42482  2011-01-04 10:00:00       0.42     13313.0  United Kingdom       10.50
42483  2011-01-04 10:00:00       0.42     13313.0  United Kingdom       10.50
42484  2011-01-04 10:00:00       2.10     13313.0  United Kingdom       10.50
42485  2011-01-04 10:00:00       1.25     13313.0  United Kingdom       12.50
...                    ...        ...         ...             ...         ...
541904 2011-12-09 12:50:00       0.85     12680.0          France       10.20
541905 2011-12-09 12:50:00       2.10     12680.0          France       12.60
541906 2011-12-09 12:50:00       4.15     12680.0          France       16.60
541907 2011-12-09 12:50:00       4.15     12680.0          France       16.60
541908 2011-12-09 12:50:00       4.95     12680.0          France       14.85

        HighValue  DiscountedPrice PriceCategory  Total_price
42481        True            1.755        Medium        19.50
42482       False            0.378        Medium        10.50
42483       False            0.378        Medium        10.50
42484       False            1.890        Medium        10.50
42485       False            1.125        Medium        12.50
...           ...              ...           ...          ...
541904      False            0.765        Medium        10.20
541905      False            1.890        Medium        12.60
541906       True            3.735        Medium        16.60
541907       True            3.735        Medium        16.60
541908      False            4.455        Medium        14.85

[499428 rows x 13 columns]

In [21]:
sales_2010 = df[
    df['InvoiceDate'].dt.year == 2010
]

print(sales_2010)

      InvoiceNo StockCode                          Description  Quantity  \
0        536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1        536365     71053                  WHITE METAL LANTERN         6
2        536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3        536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4        536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...         ...       ...                                  ...       ...
42476    539991     21618       4 WILDFLOWER BOTANICAL CANDLES         1
42477    539991     72741                GRAND CHOCOLATECANDLE         4
42478    539992     21470        FLOWER VINE RAFFIA FOOD COVER         1
42479    539992     22258              FELT FARM ANIMAL RABBIT         1
42480    539992     21155                RED RETROSPOT PEG BAG         1

              InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
0     2010-12-01 08:26:00       2.55     17850.0  United Kingdom       15.30
1     2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
2     2010-12-01 08:26:00       2.75     17850.0  United Kingdom       22.00
3     2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
4     2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
...                   ...        ...         ...             ...         ...
42476 2010-12-23 16:49:00       1.25         NaN  United Kingdom        1.25
42477 2010-12-23 16:49:00       1.45         NaN  United Kingdom        5.80
42478 2010-12-23 17:41:00       3.75         NaN  United Kingdom        3.75
42479 2010-12-23 17:41:00       1.25         NaN  United Kingdom        1.25
42480 2010-12-23 17:41:00       2.10         NaN  United Kingdom        2.10

       HighValue  DiscountedPrice PriceCategory  Total_price
0           True            2.295        Medium        15.30
1           True            3.051        Medium        20.34
2           True            2.475        Medium        22.00
3           True            3.051        Medium        20.34
4           True            3.051        Medium        20.34
...          ...              ...           ...          ...
42476      False            1.125        Medium         1.25
42477      False            1.305        Medium         5.80
42478      False            3.375        Medium         3.75
42479      False            1.125        Medium         1.25
42480      False            1.890        Medium         2.10

[42481 rows x 13 columns]

In [22]:
#filtro por año y por mes

sales_dec_2010 = df[
    (df['InvoiceDate'].dt.year == 2010)&
    (df['InvoiceDate'].dt.month == 12)
]

print(sales_dec_2010)

      InvoiceNo StockCode                          Description  Quantity  \
0        536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1        536365     71053                  WHITE METAL LANTERN         6
2        536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3        536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4        536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...         ...       ...                                  ...       ...
42476    539991     21618       4 WILDFLOWER BOTANICAL CANDLES         1
42477    539991     72741                GRAND CHOCOLATECANDLE         4
42478    539992     21470        FLOWER VINE RAFFIA FOOD COVER         1
42479    539992     22258              FELT FARM ANIMAL RABBIT         1
42480    539992     21155                RED RETROSPOT PEG BAG         1

              InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
0     2010-12-01 08:26:00       2.55     17850.0  United Kingdom       15.30
1     2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
2     2010-12-01 08:26:00       2.75     17850.0  United Kingdom       22.00
3     2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
4     2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
...                   ...        ...         ...             ...         ...
42476 2010-12-23 16:49:00       1.25         NaN  United Kingdom        1.25
42477 2010-12-23 16:49:00       1.45         NaN  United Kingdom        5.80
42478 2010-12-23 17:41:00       3.75         NaN  United Kingdom        3.75
42479 2010-12-23 17:41:00       1.25         NaN  United Kingdom        1.25
42480 2010-12-23 17:41:00       2.10         NaN  United Kingdom        2.10

       HighValue  DiscountedPrice PriceCategory  Total_price
0           True            2.295        Medium        15.30
1           True            3.051        Medium        20.34
2           True            2.475        Medium        22.00
3           True            3.051        Medium        20.34
4           True            3.051        Medium        20.34
...          ...              ...           ...          ...
42476      False            1.125        Medium         1.25
42477      False            1.305        Medium         5.80
42478      False            3.375        Medium         3.75
42479      False            1.125        Medium         1.25
42480      False            1.890        Medium         2.10

[42481 rows x 13 columns]

In [23]:
# PIVOT TABLE PARA REORGANIZAR LA INFORMACION

pivot_table = pd.pivot_table(df, values= 'Quantity', index= 'Country',columns= ['StockCode','CustomerID'],aggfunc= 'mean')
pivot_table

StockCode              10002                                                  \
CustomerID           12451.0 12510.0 12583.0 12637.0 12673.0 12681.0 12682.0
Country
Australia                NaN     NaN     NaN     NaN     NaN     NaN     NaN
Austria                  NaN     NaN     NaN     NaN     NaN     NaN     NaN
Bahrain                  NaN     NaN     NaN     NaN     NaN     NaN     NaN
Belgium                  NaN     NaN     NaN     NaN     NaN     NaN     NaN
Brazil                   NaN     NaN     NaN     NaN     NaN     NaN     NaN
Canada                   NaN     NaN     NaN     NaN     NaN     NaN     NaN
Channel Islands          NaN     NaN     NaN     NaN     NaN     NaN     NaN
Cyprus                   NaN     NaN     NaN     NaN     NaN     NaN     NaN
Czech Republic           NaN     NaN     NaN     NaN     NaN     NaN     NaN
Denmark                  NaN     NaN     NaN     NaN     NaN     NaN     NaN
EIRE                     NaN     NaN     NaN     NaN     NaN     NaN     NaN
European Community       NaN     NaN     NaN     NaN     NaN     NaN     NaN
Finland                  NaN     NaN     NaN     NaN     NaN     NaN     NaN
France                   NaN     NaN    48.0    12.0     NaN    12.0    12.0
Germany                  NaN     NaN     NaN     NaN     1.0     NaN     NaN
Greece                   NaN     NaN     NaN     NaN     NaN     NaN     NaN
Iceland                  NaN     NaN     NaN     NaN     NaN     NaN     NaN
Israel                   NaN     NaN     NaN     NaN     NaN     NaN     NaN
Italy                    NaN     NaN     NaN     NaN     NaN     NaN     NaN
Japan                    NaN     NaN     NaN     NaN     NaN     NaN     NaN
Lebanon                  NaN     NaN     NaN     NaN     NaN     NaN     NaN
Lithuania                NaN     NaN     NaN     NaN     NaN     NaN     NaN
Malta                    NaN     NaN     NaN     NaN     NaN     NaN     NaN
Netherlands              NaN     NaN     NaN     NaN     NaN     NaN     NaN
Norway                   NaN     NaN     NaN     NaN     NaN     NaN     NaN
Poland                   NaN     NaN     NaN     NaN     NaN     NaN     NaN
Portugal                 NaN     NaN     NaN     NaN     NaN     NaN     NaN
RSA                      NaN     NaN     NaN     NaN     NaN     NaN     NaN
Saudi Arabia             NaN     NaN     NaN     NaN     NaN     NaN     NaN
Singapore                NaN     NaN     NaN     NaN     NaN     NaN     NaN
Spain                    NaN    24.0     NaN     NaN     NaN     NaN     NaN
Sweden                   NaN     NaN     NaN     NaN     NaN     NaN     NaN
Switzerland             12.0     NaN     NaN     NaN     NaN     NaN     NaN
USA                      NaN     NaN     NaN     NaN     NaN     NaN     NaN
United Arab Emirates     NaN     NaN     NaN     NaN     NaN     NaN     NaN
United Kingdom           NaN     NaN     NaN     NaN     NaN     NaN     NaN
Unspecified              NaN     NaN     NaN     NaN     NaN     NaN     NaN

StockCode                                     ...    POST                  \
CustomerID           12731.0 12748.0 12754.0  ... 17552.0 17612.0 17676.0
Country                                       ...
Australia                NaN     NaN     NaN  ...     NaN     NaN     NaN
Austria                  NaN     NaN     NaN  ...     NaN     NaN     NaN
Bahrain                  NaN     NaN     NaN  ...     NaN     NaN     NaN
Belgium                  NaN     NaN     NaN  ...     NaN     NaN     NaN
Brazil                   NaN     NaN     NaN  ...     NaN     NaN     NaN
Canada                   NaN     NaN     NaN  ...     NaN     NaN     NaN
Channel Islands          NaN     NaN     NaN  ...     NaN     NaN     NaN
Cyprus                   NaN     NaN     NaN  ...     NaN     NaN     NaN
Czech Republic           NaN     NaN     NaN  ...     NaN     NaN     NaN
Denmark                  NaN     NaN     NaN  ...     NaN     NaN     NaN
EIRE                     NaN     NaN     NaN  ...     NaN     NaN     NaN
European Community       NaN     NaN     NaN  ...     NaN     NaN     NaN
Finland                  NaN     NaN     NaN  ...     NaN     NaN     NaN
France                  92.0     NaN     NaN  ...     NaN     NaN     NaN
Germany                  NaN     NaN     NaN  ...     NaN     NaN     NaN
Greece                   NaN     NaN     NaN  ...     NaN     NaN     NaN
Iceland                  NaN     NaN     NaN  ...     NaN     NaN     NaN
Israel                   NaN     NaN     NaN  ...     NaN     NaN     NaN
Italy                    NaN     NaN     NaN  ...     NaN     NaN     NaN
Japan                    NaN     NaN     1.0  ...     NaN     NaN     NaN
Lebanon                  NaN     NaN     NaN  ...     NaN     NaN     NaN
Lithuania                NaN     NaN     NaN  ...     NaN     NaN     NaN
Malta                    NaN     NaN     NaN  ...     NaN     NaN     NaN
Netherlands              NaN     NaN     NaN  ...     NaN     NaN     NaN
Norway                   NaN     NaN     NaN  ...     NaN     NaN     NaN
Poland                   NaN     NaN     NaN  ...     NaN     NaN     NaN
Portugal                 NaN     NaN     NaN  ...     NaN     NaN     NaN
RSA                      NaN     NaN     NaN  ...     NaN     NaN     NaN
Saudi Arabia             NaN     NaN     NaN  ...     NaN     NaN     NaN
Singapore                NaN     NaN     NaN  ...     NaN     NaN     NaN
Spain                    NaN     NaN     NaN  ...     NaN     NaN     NaN
Sweden                   NaN     NaN     NaN  ...     NaN     NaN     NaN
Switzerland              NaN     NaN     NaN  ...     NaN     NaN     NaN
USA                      NaN     NaN     NaN  ...     NaN     NaN     NaN
United Arab Emirates     NaN     NaN     NaN  ...     NaN     NaN     NaN
United Kingdom           NaN     1.0     NaN  ...    -1.0    -1.0    -1.0
Unspecified              NaN     NaN     NaN  ...     NaN     NaN     NaN

StockCode
CustomerID           17788.0 17828.0 17935.0 17940.0 18223.0 18257.0 18270.0
Country
Australia                NaN     NaN     NaN     NaN     NaN     NaN     NaN
Austria                  NaN     NaN     NaN     NaN     NaN     NaN     NaN
Bahrain                  NaN     NaN     NaN     NaN     NaN     NaN     NaN
Belgium                  NaN     NaN     NaN     NaN     NaN     NaN     NaN
Brazil                   NaN     NaN     NaN     NaN     NaN     NaN     NaN
Canada                   NaN     NaN     NaN     NaN     NaN     NaN     NaN
Channel Islands          NaN     NaN     NaN     NaN     NaN     NaN     NaN
Cyprus                   NaN     NaN     NaN     NaN     NaN     NaN     NaN
Czech Republic           NaN     NaN     NaN     NaN     NaN     NaN     NaN
Denmark                  NaN     NaN     NaN     NaN     NaN     NaN     NaN
EIRE                     NaN     NaN     NaN     NaN     NaN     NaN     NaN
European Community       NaN     NaN     NaN     NaN     NaN     NaN     NaN
Finland                  NaN     NaN     NaN     NaN     NaN     NaN     NaN
France                   NaN     NaN     NaN     NaN     NaN     NaN     NaN
Germany                  NaN     NaN     NaN     NaN     NaN     NaN     NaN
Greece                   NaN     NaN     NaN     NaN     NaN     NaN     NaN
Iceland                  NaN     NaN     NaN     NaN     NaN     NaN     NaN
Israel                   NaN     NaN     NaN     NaN     NaN     NaN     NaN
Italy                    NaN     NaN     NaN     NaN     NaN     NaN     NaN
Japan                    NaN     NaN     NaN     NaN     NaN     NaN     NaN
Lebanon                  NaN     NaN     NaN     NaN     NaN     NaN     NaN
Lithuania                NaN     NaN     NaN     NaN     NaN     NaN     NaN
Malta                    NaN     2.5     NaN     NaN     NaN     NaN     NaN
Netherlands              NaN     NaN     NaN     NaN     NaN     NaN     NaN
Norway                   NaN     NaN     NaN     NaN     NaN     NaN     NaN
Poland                   NaN     NaN     NaN     NaN     NaN     NaN     NaN
Portugal                 NaN     NaN     NaN     NaN     NaN     NaN     NaN
RSA                      NaN     NaN     NaN     NaN     NaN     NaN     NaN
Saudi Arabia             NaN     NaN     NaN     NaN     NaN     NaN     NaN
Singapore                NaN     NaN     NaN     NaN     NaN     NaN     NaN
Spain                    NaN     NaN     NaN     NaN     NaN     NaN     NaN
Sweden                   NaN     NaN     NaN     NaN     NaN     NaN     NaN
Switzerland              NaN     NaN     NaN     NaN     NaN     NaN     NaN
USA                      NaN     NaN     NaN     NaN     NaN     NaN     NaN
United Arab Emirates     NaN     NaN     NaN     NaN     NaN     NaN     NaN
United Kingdom           1.0     NaN     1.0    -1.0    -1.0    -1.0    -1.0
Unspecified              NaN     NaN     NaN     NaN     NaN     NaN     NaN

[37 rows x 267615 columns]

In [24]:
#  apilar y desaplilar informacion con pandas

df_apilar = pd.DataFrame({
    'A':['foo','bar','baz'],
    'B':[1,2,3],
    'C':[4,5,6]
})

df_apilar

     A  B  C
0  foo  1  4
1  bar  2  5
2  baz  3  6

In [25]:
# tranformacion de los indices de filas a columnas (APILAR)
df_stacked = df_apilar.stack()
df_stacked

0  A    foo
   B      1
   C      4
1  A    bar
   B      2
   C      5
2  A    baz
   B      3
   C      6
dtype: object

In [26]:
df_unstacked = df_stacked.unstack()
df_unstacked

     A  B  C
0  foo  1  4
1  bar  2  5
2  baz  3  6

In [27]:
# CRUCES DE DATAFRAMES MERGE JOIN

import pandas as pd

# Crear DataFrames de ejemplo
df1 = pd.DataFrame({
    'key': ['A', 'B', 'C'],
    'value1': [1, 2, 3]
})

df2 = pd.DataFrame({
    'key': ['B', 'C', 'D'],
    'value2': [4, 5, 6]
})

print(df1)
print(df2)

  key  value1
0   A       1
1   B       2
2   C       3
  key  value2
0   B       4
1   C       5
2   D       6

In [28]:
inner_merge = pd.merge(df1,df2, on= 'key', how= 'inner')
inner_merge

  key  value1  value2
0   B       2       4
1   C       3       5

In [29]:
# combina el total de los datos de los dateframes
outer_merger = pd.merge(df1,df2,on='key', how= 'outer')
outer_merger

  key  value1  value2
0   A     1.0     NaN
1   B     2.0     4.0
2   C     3.0     5.0
3   D     NaN     6.0

In [30]:
# merge a la izquierda
left_merge = pd.merge(df1,df2, on= 'key', how= 'left')
left_merge

  key  value1  value2
0   A       1     NaN
1   B       2     4.0
2   C       3     5.0

In [31]:
# merge a la izquierda
right_merge = pd.merge(df1,df2, on= 'key', how= 'right')
right_merge

  key  value1  value2
0   B     2.0       4
1   C     3.0       5
2   D     NaN       6

In [32]:
# concatenar dataframes vertical u horizontal
# Crear DataFrames de ejemplo
df3 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2']
})
    
df4 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5']
})

print(df3)
print(df4)

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
    A   B
0  A3  B3
1  A4  B4
2  A5  B5

In [33]:
# concatenar vertical
vertical_concat = pd.concat([df3,df4])

vertical_concat

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
0  A3  B3
1  A4  B4
2  A5  B5

In [34]:
# concatenar horizontal
horizontal_concat = pd.concat([df3,df4],axis= 1)
horizontal_concat

horizontal_concat

    A   B   A   B
0  A0  B0  A3  B3
1  A1  B1  A4  B4
2  A2  B2  A5  B5

In [35]:
#  joined unir dateframes por indices o columna clave

# Crear DataFrames de ejemplo con índices
df5 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2']
}, index=['K0', 'K1', 'K2'])

df6 = pd.DataFrame({
    'C': ['C0', 'C1', 'C2'],
    'D': ['D0', 'D1', 'D2']
}, index=['K0', 'K2', 'K3'])

print(df5)
print(df6)

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2
     C   D
K0  C0  D0
K2  C1  D1
K3  C2  D2

In [36]:
joined = df5.join(df6,how='inner')
joined

     A   B   C   D
K0  A0  B0  C0  D0
K2  A2  B2  C1  D1

In [37]:
######  MANEJO DE FECHAS PARA DATOS TEMPORALES
# usamos el dataset csv cargado
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,HighValue,DiscountedPrice,PriceCategory,Total_price
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,True,2.295,Medium,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,True,3.051,Medium,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,True,2.475,Medium,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,True,3.051,Medium,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,True,3.051,Medium,20.34

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 13 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   InvoiceNo        541909 non-null  object
 1   StockCode        541909 non-null  object
 2   Description      540455 non-null  object
 3   Quantity         541909 non-null  int64
 4   InvoiceDate      541909 non-null  datetime64[ns]
 5   UnitPrice        541909 non-null  float64
 6   CustomerID       406829 non-null  float64
 7   Country          541909 non-null  object
 8   TotalPrice       541909 non-null  float64
 9   HighValue        541909 non-null  bool
 10  DiscountedPrice  541909 non-null  float64
 11  PriceCategory    539007 non-null  object
 12  Total_price      541909 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(5), int64(1), object(5)
memory usage: 50.1+ MB

In [39]:
# eliminar los nullos  el inplace es para remplazar dentro del mismo dataframe

df.dropna(subset=['InvoiceDate'],inplace= True)
df.head(3)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,HighValue,DiscountedPrice,PriceCategory,Total_price
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,True,2.295,Medium,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,True,3.051,Medium,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,True,2.475,Medium,22.00

In [40]:
df.set_index('InvoiceDate',inplace= True)
print(df.head(3))

                    InvoiceNo StockCode                         Description  \
InvoiceDate
2010-12-01 08:26:00    536365    85123A  WHITE HANGING HEART T-LIGHT HOLDER
2010-12-01 08:26:00    536365     71053                 WHITE METAL LANTERN
2010-12-01 08:26:00    536365    84406B      CREAM CUPID HEARTS COAT HANGER

                     Quantity  UnitPrice  CustomerID         Country  \
InvoiceDate
2010-12-01 08:26:00         6       2.55     17850.0  United Kingdom
2010-12-01 08:26:00         6       3.39     17850.0  United Kingdom
2010-12-01 08:26:00         8       2.75     17850.0  United Kingdom

                     TotalPrice  HighValue  DiscountedPrice PriceCategory  \
InvoiceDate
2010-12-01 08:26:00       15.30       True            2.295        Medium
2010-12-01 08:26:00       20.34       True            3.051        Medium
2010-12-01 08:26:00       22.00       True            2.475        Medium

                     Total_price
InvoiceDate
2010-12-01 08:26:00        15.30
2010-12-01 08:26:00        20.34
2010-12-01 08:26:00        22.00

In [ ]:
#  descomponer la fecha

df['Year'] = df.index.year
df['Month'] = df.index.month
df['day'] = df.index.day
df['weekday'] = df.index.weekday
df['Hour'] = df.index.hour
print(df['Year'])
print(df['Hour'])

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,TotalPrice,HighValue,DiscountedPrice,PriceCategory,Total_price,Year,Month,day,weekday,Hour
InvoiceDate,,,,,,,,,,,,,,,,,
2010-12-01 08:26:00,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850.0,United Kingdom,15.30,True,2.295,Medium,15.30,2010,12,1,2,8
2010-12-01 08:26:00,536365,71053,WHITE METAL LANTERN,6,3.39,17850.0,United Kingdom,20.34,True,3.051,Medium,20.34,2010,12,1,2,8
2010-12-01 08:26:00,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850.0,United Kingdom,22.00,True,2.475,Medium,22.00,2010,12,1,2,8

In [48]:
# eliminar columnas
df = df.drop(columns=['weekday'])
df.head(3)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,TotalPrice,HighValue,DiscountedPrice,PriceCategory,Total_price,Year,Month,day,Hour
InvoiceDate,,,,,,,,,,,,,,,,
2010-12-01 08:26:00,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850.0,United Kingdom,15.30,True,2.295,Medium,15.30,2010,12,1,8
2010-12-01 08:26:00,536365,71053,WHITE METAL LANTERN,6,3.39,17850.0,United Kingdom,20.34,True,3.051,Medium,20.34,2010,12,1,8
2010-12-01 08:26:00,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850.0,United Kingdom,22.00,True,2.475,Medium,22.00,2010,12,1,8

In [49]:
df['weekday'] = df.index.weekday
df.head(3)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,TotalPrice,HighValue,DiscountedPrice,PriceCategory,Total_price,Year,Month,day,Hour,weekday
InvoiceDate,,,,,,,,,,,,,,,,,
2010-12-01 08:26:00,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850.0,United Kingdom,15.30,True,2.295,Medium,15.30,2010,12,1,8,2
2010-12-01 08:26:00,536365,71053,WHITE METAL LANTERN,6,3.39,17850.0,United Kingdom,20.34,True,3.051,Medium,20.34,2010,12,1,8,2
2010-12-01 08:26:00,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850.0,United Kingdom,22.00,True,2.475,Medium,22.00,2010,12,1,8,2

In [ ]:
# extraer la info a partir del indice datetime con loc
df_2011 = df.loc['2011']
df_2011.head(3)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,TotalPrice,HighValue,DiscountedPrice,PriceCategory,Total_price,Year,Month,day,Hour,weekday
InvoiceDate,,,,,,,,,,,,,,,,,
2011-01-04 10:00:00,539993,22386,JUMBO BAG PINK POLKADOT,10,1.95,13313.0,United Kingdom,19.5,True,1.755,Medium,19.5,2011,1,4,10,1
2011-01-04 10:00:00,539993,21499,BLUE POLKADOT WRAP,25,0.42,13313.0,United Kingdom,10.5,False,0.378,Medium,10.5,2011,1,4,10,1
2011-01-04 10:00:00,539993,21498,RED RETROSPOT WRAP,25,0.42,13313.0,United Kingdom,10.5,False,0.378,Medium,10.5,2011,1,4,10,1

In [52]:
df_2011_dic = df.loc['2011-12']
df_2011_dic.head(3)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,TotalPrice,HighValue,DiscountedPrice,PriceCategory,Total_price,Year,Month,day,Hour,weekday
InvoiceDate,,,,,,,,,,,,,,,,,
2011-12-01 08:12:00,C579889,23245,SET OF 3 REGENCY CAKE TINS,-8,4.15,13853.0,United Kingdom,-33.20,False,3.735,Medium,-33.20,2011,12,1,8,3
2011-12-01 08:14:00,C579890,84947,ANTIQUE SILVER TEA GLASS ENGRAVED,-1,1.25,15197.0,United Kingdom,-1.25,False,1.125,Medium,-1.25,2011,12,1,8,3
2011-12-01 08:14:00,C579890,23374,RED SPOT PAPER GIFT BAG,-1,0.82,15197.0,United Kingdom,-0.82,False,0.738,Medium,-0.82,2011,12,1,8,3

In [ ]:
#  filtar por rango de tiempos del index
df_dec_range = df.loc['2010-12-01':'2010-12-15']
df_dec_range.head()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,TotalPrice,HighValue,DiscountedPrice,PriceCategory,Total_price,Year,Month,day,Hour,weekday
InvoiceDate,,,,,,,,,,,,,,,,,
2010-12-01 08:26:00,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850.0,United Kingdom,15.30,True,2.295,Medium,15.30,2010,12,1,8,2
2010-12-01 08:26:00,536365,71053,WHITE METAL LANTERN,6,3.39,17850.0,United Kingdom,20.34,True,3.051,Medium,20.34,2010,12,1,8,2
2010-12-01 08:26:00,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850.0,United Kingdom,22.00,True,2.475,Medium,22.00,2010,12,1,8,2
2010-12-01 08:26:00,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850.0,United Kingdom,20.34,True,3.051,Medium,20.34,2010,12,1,8,2
2010-12-01 08:26:00,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,17850.0,United Kingdom,20.34,True,3.051,Medium,20.34,2010,12,1,8,2

In [56]:
# crear rangos de fechas con informacion nueva esto queda creadocomo una serie

date_range_new = pd.date_range(start='2024-01-01', end= '2024-12-31', freq= 'D')
date_range_new

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10',
               ...
               '2024-12-22', '2024-12-23', '2024-12-24', '2024-12-25',
               '2024-12-26', '2024-12-27', '2024-12-28', '2024-12-29',
               '2024-12-30', '2024-12-31'],
              dtype='datetime64[ns]', length=366, freq='D')

In [57]:
df_dates = pd.DataFrame(date_range_new, columns= ['Date'])
df_dates.head()

        Date
0 2024-01-01
1 2024-01-02
2 2024-01-03
3 2024-01-04
4 2024-01-05

In [58]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,TotalPrice,HighValue,DiscountedPrice,PriceCategory,Total_price,Year,Month,day,Hour,weekday
InvoiceDate,,,,,,,,,,,,,,,,,
2010-12-01 08:26:00,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850.0,United Kingdom,15.30,True,2.295,Medium,15.30,2010,12,1,8,2
2010-12-01 08:26:00,536365,71053,WHITE METAL LANTERN,6,3.39,17850.0,United Kingdom,20.34,True,3.051,Medium,20.34,2010,12,1,8,2
2010-12-01 08:26:00,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850.0,United Kingdom,22.00,True,2.475,Medium,22.00,2010,12,1,8,2
2010-12-01 08:26:00,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850.0,United Kingdom,20.34,True,3.051,Medium,20.34,2010,12,1,8,2
2010-12-01 08:26:00,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,17850.0,United Kingdom,20.34,True,3.051,Medium,20.34,2010,12,1,8,2

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 541909 entries, 2010-12-01 08:26:00 to 2011-12-09 12:50:00
Data columns (total 17 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   InvoiceNo        541909 non-null  object
 1   StockCode        541909 non-null  object
 2   Description      540455 non-null  object
 3   Quantity         541909 non-null  int64
 4   UnitPrice        541909 non-null  float64
 5   CustomerID       406829 non-null  float64
 6   Country          541909 non-null  object
 7   TotalPrice       541909 non-null  float64
 8   HighValue        541909 non-null  bool
 9   DiscountedPrice  541909 non-null  float64
 10  PriceCategory    539007 non-null  object
 11  Total_price      541909 non-null  float64
 12  Year             541909 non-null  int32
 13  Month            541909 non-null  int32
 14  day              541909 non-null  int32
 15  Hour             541909 non-null  int32
 16  weekday          541909 non-null  int32
dtypes: bool(1), float64(5), int32(5), int64(1), object(5)
memory usage: 76.6+ MB

In [69]:
df_2011_2 = df[
    (df['Year'] == 2011) &
    (df['Month'] == 10)
][
    [
        'Country',
        'CustomerID',
        'Description'
    ]
].sort_values(by= 'CustomerID', ascending= True).reset_index()

df_2011_2

,InvoiceDate,Country,CustomerID,Description
0,2011-10-31 12:25:00,Iceland,12347.0,SET OF 60 VINTAGE LEAF CAKE CASES
1,2011-10-31 12:25:00,Iceland,12347.0,WOODEN SCHOOL COLOURING SET
2,2011-10-31 12:25:00,Iceland,12347.0,REVOLVER WOODEN RULER
3,2011-10-31 12:25:00,Iceland,12347.0,PLAYING CARDS KEEP CALM & CARRY ON
4,2011-10-31 12:25:00,Iceland,12347.0,MINI PLAYING CARDS SPACEBOY
...,...,...,...,...
60737,2011-10-31 16:49:00,United Kingdom,NaN,POSTAGE
60738,2011-10-31 17:02:00,United Kingdom,NaN,check
60739,2011-10-31 17:04:00,United Kingdom,NaN,check
60740,2011-10-31 17:18:00,United Kingdom,NaN,check
60741,2011-10-31 17:19:00,United Kingdom,NaN,check

In [72]:
df_retail_group = df.groupby(
    ['Description',
     'Country',
     'PriceCategory'
     ]
).agg(
    total_price = ('TotalPrice', 'sum'),
    unit_price_total = ('UnitPrice','sum'),
    total_stock = ('Quantity', ('count'))
).sort_values(by= 'total_price', ascending= False).reset_index()

df_retail_group

,Description,Country,PriceCategory,total_price,unit_price_total,total_stock
0,DOTCOM POSTAGE,United Kingdom,Hight,205342.10,205342.10,669
1,REGENCY CAKESTAND 3 TIER,United Kingdom,Medium,107418.47,19971.81,1612
2,WHITE HANGING HEART T-LIGHT HOLDER,United Kingdom,Medium,93953.07,7309.77,2271
3,PARTY BUNTING,United Kingdom,Medium,92501.73,9532.07,1634
4,JUMBO BAG RED RETROSPOT,United Kingdom,Medium,84516.44,5015.27,2001
...,...,...,...,...,...,...
20136,Bank Charges,United Kingdom,Hight,-7192.23,7192.23,21
20137,CRUK Commission,United Kingdom,Hight,-7902.86,7902.86,13
20138,Adjust bad debt,United Kingdom,Medium,-22124.12,-22124.12,2
20139,Manual,United Kingdom,Hight,-67137.25,128415.39,148
20140,AMAZON FEE,United Kingdom,Hight,-221519.50,249041.68,33